resource_group_name  = "ResourceGroup1"
location             = "West US 2"
container_group_name = "scontainer1"
container_name       = "scontainer1"
container_image      = "ubuntu"
dns_name_label       = "scontainer1"
